baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'bilecik '

[blackfriday]
  unsafe = true

  
[Params]

MainAboutTitle = 'الرسالة : '
AboutTitle = 'رسالة الرابطة تتمثل في تعزيز الترابط والتعاون المجتمعي، وتعزيز الوعي والتنمية الشاملة لأفراد المجتمع. نسعى إلى بناء جيل واعٍ ومسؤول يسهم في تحقيق التنمية المستدامة والازدهار الاجتماعي. '

MainAboutMission = 'alhady '
AboutMission = 'testType is here '

MainAboutOffers = 'testType is here '
AboutOffers = 'testType is here '

MainAboutTeam = 'test type  '
AboutTeam = 'testType is here '

MainAboutVison = 'testType is here '
AboutVison = 'testType is here '